### ISSUE TITLE
Add Description for Social Media Icons When Hovered Upon

### ISSUE THREAD

**Issue by egladman** [CWDG/open-source-club-website#10]

**Comment by egladman** [comment]
For example when the  mouse hovers over the facebook icon, a tooltip should pop up saying "facebook". We are going to use this CSS Library: http://kushagragour.in/lab/hint/ You might want to read through this https://developer.mozilla.org/en-US/docs/Web/CSS/:hover

**Comment by deadant2** [comment]
I am looking at a freshly cloned copy of the website and I dont see social media icons at all. I could add social media Icons if somebody gives them to me. Also I think I will change the centering on the text on the IRC page bacause it looks weird centered http://imgur.com/Ga7ekaP, but I should be able to make a rule that just applies to that. Oh and also ᴵ ᵈᵒᶰᵗ ᵉˣᵃᶜᵗᶫʸ ᵏᶰᵒʷ ʰᵒʷ ᵗᵒ ᵖᵘᵗ ˢᵒᵐᵉᵗʰᶦᶰᵍ ᵇᵃᶜᵏ ᵒᶰᵗᵒ ᵍᶦᵗʰᵘᵇ
