### ISSUE TITLE
LibreJS Support

### ISSUE THREAD

**Issue by keeakita** [CWDG/open-source-club-website#102]
https://www.gnu.org/software/librejs/

Since all JS on our site is free software (it is, right?), we can add headers for LibreJS users to let them know this is the case. LibreJS blocks nonfree javascript by default, and will block our site since it doesn't know our JS is free.

It's super low priority, but something I've considered working on myself. I'll need more info about how we minify javascript right now (does it all get shoved into on JS, including libraries?).

**Comment by egladman** [comment]
yes, all of our js would comply.

I intend to concatenate ALL of our js to reduce the amount of http requests. I really don't like the idea of   LIbreJS. But currently libraries are minified separately.

I don't like the idea of including each license in the http request. I would rather save the bandwidth.

I haven't been too vocal about this here on this repository, but I'd like reduce the DOM load time as much as possible.

**Comment by egladman** [comment]
@oslerw if this something you want to pursue by all means go for it, however I will be unable to assist.

**Comment by keeakita** [comment]
That's fine, its a nice to have extra. I'd be solely responsible for it if I ever pursued it.

**Comment by egladman** [comment]
This issue has been stale for awhile. @oslerw Any thoughts on if you are going to pursue it.

**Comment by keeakita** [comment]
Probably not, given the friction involved in getting permission from my
employer to contribute to FOSS projects and the fact that honestly, nobody
uses LibreJS anyway.
