### ISSUE TITLE
post linter

### ISSUE THREAD

**Issue by egladman** [CWDG/open-source-club-website#105]
It would be nice to have a rake test / grunt task check post syntax and format

goals
- check for "legal" markdown (including tables)
- wrap text if it exceeds 80 characters
- check for YAML Front Matter block
- check for post signature
- some sort of spell checking
- ~~check that the post title doesn't contain "illegal" characters~~

**Comment by egladman** [comment]
It might help to checkout the [post generator script](https://github.com/OSUOSC/open-source-club-website/blob/master/_helper/new-post.sh)

**Comment by egladman** [comment]
This should be written in ruby

**Comment by egladman** [comment]
this feature should be added to the Rakefile. Since it would take ages to validate every post i purpose we only test the most recent post. You can easily determine the latest post since each post has the publication date in it's name.

#### requirements
- spell check
  - use [hunspell](https://github.com/segabor/Hunspell)?
- check for YAML Front Matter block
  - this can be accomplished with some simple regex
- validate markdown
  - use [bluecloth](https://rubygems.org/gems/bluecloth)?

#### optional
- check for post signature
- wrap lines that exceed 80 characters

**Comment by egladman** [comment]
add to Hacktoberfest?

**Comment by smacz42** [comment]
Will not build with illegal markdown
