### ISSUE TITLE
Disproportionate Layout at High Resolution

### ISSUE THREAD

**Issue by teaganstrayed** [CWDG/open-source-club-website#108]
Res: 2560 x 1600
![image](https://cloud.githubusercontent.com/assets/10553067/10948046/87603dc2-82f9-11e5-8584-bf270c304485.png)

**Comment by egladman** [comment]
@cjadams13 should be fixed now. Checkout the changes on our [staging site](http://osuosc.github.io/open-source-club-website/). Let me know if this indeed fixed the issue. Thanks.

**Comment by teaganstrayed** [comment]
It still seems to be the same. I’ve tested it on the staging site link and on the official site link.

[cid:BDE0BD2B-62A3-4E8D-B25F-8185CA236F07@attlocal.net]
On Nov 11, 2015, at 09:17, Eli Gladman <notifications@github.com<mailto:notifications@github.com>> wrote:

@cjadams13https://github.com/cjadams13 should be fixed now. Checkout the changes on our staging sitehttp://osuosc.github.io/open-source-club-website/. Let me know if this indeed fixed the issue. Thanks.

**Comment by egladman** [comment]
@cjadams13  What about now? Our [staging site](https://osuosc.github.io/open-source-club-website/) should have the issue fixed. Mind checking?

**Comment by egladman** [comment]
I believe this is fixed, if it isn't go ahead and reopen
