### ISSUE TITLE
add animation/ fade-in effect to back to top button

### ISSUE THREAD

**Issue by egladman** [CWDG/open-source-club-website#124]
Currently the button just appears out of thin air, and comes across as jagged/incomplete.

**Comment by calvinrbnspiess** [comment]
Hey,
I want to help out. Can I still take this issue?
Please get me right, you want the button to fade in slowly while you are scrolling down the page, or?
Thanks.

**Comment by smacz42** [comment]
#### WILL NOT FIX - new site
