### ISSUE TITLE
All meeting announcements that are posted should list the meeting time and room number

### ISSUE THREAD

**Issue by egladman** [CWDG/open-source-club-website#131]
the last two posts by @moore3071 and @Nefari0uss did not include the meeting time or room number. 

@moore3071 don't deviate from the "typical" announcement post unless you are 100% certain you included all pertinent meeting details.

**Comment by Nefari0uss** [comment]
My bad. I used the latest post (at that time) as a template.

**Comment by egladman** [comment]
added documentation: 5938b282b2f24cf6611be3fa4a37f4990522d6bd
