### ISSUE TITLE
Accessing prior meetings is difficult and inconvenient

### ISSUE THREAD

**Issue by Nefari0uss** [CWDG/open-source-club-website#140]
It is very difficult to access prior meetings. 

Ideally you goto "meetings" and expect to find the previous semesters' meetings.
At the moment, you must goto the home page, scroll down, and then keep scrolling to find what you want (assuming you know what you want). Furthermore, you must click the next arrow rather than having the page auto load the next set of results. Search is not helpful if you do not know what the previous meetings consisted of.

Potential fix: Add under meetings tab the semesters and time period. Under each sub link, you can find the meeting post.

**Comment by egladman** [comment]
#125 addresses some of your concerns. As for the "meetings" pages, @moore3071 is tasked with importing prior semester meetings, however he has yet to get to it. (#75) 

importing prior semester meetings should be prioritized. Perhaps @moore3071 needs some motivation.

**Comment by egladman** [comment]
@Nefari0uss go checkout the latest site, _full text_ search has been implemented.

As for your other concerns, would any of the following features/revisions improve your experience on the site? 
- infinite scrolling _that falls back to the current setup if js is disabled_
- increase the post count on each page, _it's currently set at 10_
- return additional search suggestions, _currently it's limited to 10 matches_

**Comment by benlk** [comment]
Returning additional search suggestions and posts per page would be nice. Perhaps 20?

Having a dedicated `/meetings` would be nice. (#75)

**Comment by egladman** [comment]
- doubled posts per page from _10 to 20_
- increased returned search matches from _10 to 15_

changes are now [live](https://opensource.osu.edu/)

**Comment by egladman** [comment]
- individual posts now have a "related posts" section
- pagination links are now located at the top and bottom of the page
- improved tagging and breadcrumbs
- implemented [opensource.osu.edu/latest](https:///opensource.osu.edu/latest) for frequent users

**Comment by egladman** [comment]
After further review, I renamed the path `/meetings` to `/schedules`, in addition to renaming the sidebar name. 

Let me know if you aren't satisfied with this issue's resolution.

**Comment by Nefari0uss** [comment]
@egladman Is it possible to add the meeting list from all the previous semesters? (2014 and previous). I know we have the meeting blurbs somewhere ~ some even had some very useful slides.

**Comment by egladman** [comment]
@Nefari0uss that is #75. Since @moore3071 is the librarian I consider it his responsibility. I personally don't have the time to do this.

**Comment by smacz42** [comment]
Much easier in new site
