### ISSUE TITLE
`fork on github` banner too far right on Firefox for Android

### ISSUE THREAD

**Issue by moore3071** [CWDG/open-source-club-website#146]
On Firefox for Android the fork on github banner is too far to the right and adds unnecessary horizontal scrolling  blank white space on the right sside

**Comment by egladman** [comment]
hmmmm i thought i already made an issue for this . . . anyway this a documented bug with firefox. To fix it currently requires me to go out of my way, with regards to styling.

**Comment by moore3071** [comment]
My mistake. I was just browsing the site on FF on my phone and thought I'd pop that issue up. Closing as a duplicate.

**Comment by egladman** [comment]
I can't find any prior issues referencing this bug so I'll go ahead and keep this issue open.
