### ISSUE TITLE
rename /rss.xml to /atom.xml

### ISSUE THREAD

**Issue by egladman** [CWDG/open-source-club-website#155]
The post feed will renamed to `atom.xml` in the upcoming `v1.0.0` release. Awhile back, the feed used RSS however that is no longer the case. Since Atom is used, it makes since to correct the filename.

As of right now `/atom.xml` should be made the primary feed. Until we reach `v1.0.0`  `/atom.xml` will be symlinked to `/rss.xml`, as to provide backwards compatibility.

**Comment by benlk** [comment]
:+1:

**Comment by egladman** [comment]
as of `v0.2.1` `rss.xml` is aliased to `atom.xml` and will be removed in `v1.0.0`

**Comment by smacz42** [comment]
renamed to feed.xml
