### ISSUE TITLE
Spring 2016 Semester Talks

### ISSUE THREAD

**Issue by egladman** [CWDG/open-source-club-website#158]
_moved from [here](https://github.com/OSUOSC/osuosc-website/issues/2)_

William Osler - OpenRCT2
John Markiewicz - wmultils/swn OR emacs for vim users (jmarkiewicz@airmail.cc)
Alex Fuhr - TBA
Ben Keith - Best of NICAR 2016
Nikit Malkan - KODI and media libraries
Nikit Malkan - maybe gaming on Linux.

Requests: tasker
### update

Nikit & William - Linux and Open Source Gaming

Alex - BTC

Brandon - GNU/Linux History

Fuhr - Audio

Brandon & Cody - Digital Audio

John (EDT) - Emacs for Vim users

@benlk - Best of NICAR 2016

Dan - Blender

Nikit & Bam - Git

Matt Curtin

Security Club

Paradigm - Bedrock Linux

Nikit - Regular Expressions

William/Nikit - dot file setup

John - Bricking Android :)

**Comment by egladman** [comment]
@Nefari0uss @moore3071 
This is the [file](https://github.com/OSUOSC/open-source-club-website/blob/master/_posts/2015-12-22-semester-schedule.md) that needs updated

**Comment by benlk** [comment]
NICAR is March 10 to March 13, but the following Thursday is March 17: Spring Break. I'm going to pencil my talk in for March 24, in a PR: #162

**Comment by paradigm** [comment]
Per @benlk's recommendation, I picked a date to present Bedrock Linux and created a PR: https://github.com/OSUOSC/open-source-club-website/pull/163

**Comment by kriegersaurusrex** [comment]
Cool. Next few from what I know: 
2-4: Alex Fuhr: Pure Data
2-11: Brandon Moore: Git
2-18: J3RN: Vim
2-25: Matt Curtin: Forensic Data Analysis

**Comment by egladman** [comment]
@kriegersaurusrex that is the **last time** I'm updating the schedule. It is your responsibility to promptly update the meeting schedule and site content.

**Comment by Nefari0uss** [comment]
March 10th is the date @oslerw and I are shooting for our Linux Gaming talk.

**Comment by kriegersaurusrex** [comment]
@Nefari0uss sounds good. March 3rd is the weekend before the makeathon; if we want to find a hardware-oriented talk for that day.

**Comment by kriegersaurusrex** [comment]
April 14th: Nick Wolff, FreeBSD

**Comment by egladman** [comment]
looks like we scheduled talks for all of our meetings.
