### ISSUE TITLE
create CONTRIBUTING.md

### ISSUE THREAD

**Issue by egladman** [CWDG/open-source-club-website#164]
this was originally suggested by @benlk

**Comment by benlk** [comment]
Sample contributing.md: https://github.com/INN/Largo/blob/master/contributing.md

Key points:
- workflow
- style guide
- standards

**Comment by egladman** [comment]
style guide has yet to be addressed

**Comment by benlk** [comment]
Code styles, for the most part. Tabs? Spaces? How many spaces is a tab worth? Which line do braces go on? Spaces inside and/or outside parens?
