### ISSUE TITLE
Font size overlapping on page 

### ISSUE THREAD

**Issue by kriegersaurusrex** [CWDG/open-source-club-website#167]
![129a22a402a69cd70b331368cddde29b](https://cloud.githubusercontent.com/assets/2245594/12690011/7eeb51b0-c6ae-11e5-9846-7df26fa0c945.png)

**Comment by egladman** [comment]
i fixed a similar issue on safari, this is a side effect of that.

@kriegersaurusrex What browser were you experiencing this on?

**Comment by egladman** [comment]
@kriegersaurusrex bump

**Comment by kriegersaurusrex** [comment]
Happens on firefox, mobile + desktop.
