### ISSUE TITLE
*Lots* of lag when scrolling on firefox mobile

### ISSUE THREAD

**Issue by kriegersaurusrex** [CWDG/open-source-club-website#181]
### Actual behavior

Site is scrolling very slowly on mobile. Other sites in other tabs work fine (have very fast speed in android settings), and it's not a result of having too many tabs open.

**Comment by egladman** [comment]
I disabled JS on firefox mobile and **still** experienced the  same lag. Therefore I'm led to believe this behavior is out of my control.

[This is a problem with Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=776030)

**Comment by kriegersaurusrex** [comment]
I disabled it and the scrolling worked fine. Is there more than one is library controlling the scrollbar?

**Comment by egladman** [comment]
@kriegersaurusrex  Head over to our [staging site](http://osuosc.github.io/open-source-club-website/) and let me know if scrolling is improved. If my hunch is correct I'll elaborate . . .

**Comment by egladman** [comment]
bump

**Comment by kriegersaurusrex** [comment]
Way better, thanks.

**Comment by egladman** [comment]
Okay, I know the underlying issue now. I will look into fixing it. I'll have to rewrite some of the jquery in vanilla js.

**Comment by egladman** [comment]
on firefox the console spits out the following:

> This site appears to use a scroll-linked positioning effect. This may not work well with asynchronous panning; see https://developers.mozilla.org/docs/Mozilla/Performance/ScrollLinkedEffects for further details and to join the discussion on related tools and features!

**Comment by smacz42** [comment]
#### WILL NOT FIX - new site
