### ISSUE TITLE
Repo needs setup docs

### ISSUE THREAD

**Issue by benlk** [CWDG/open-source-club-website#190]
This repo needs docs for getting set up after the initial clone:
- Running install tasks, with a list of install tasks and what each is used for and what it's doing:
  - `gem install bundle`
  - `bundle install`
  - `npm install`
  - `bower install`
  - and so forth...?

An even-better solution would include something like a `/docs` folder linked to from `README.md` with instructions for the above plus documentation for software dependencies:
- Documenting the Gruntfile
- Documenting the Rakefile
- Documenting the Gemfile
- Documenting the bowerfile
- Documenting `package.json`
- How to use the above to run the development server

**Comment by egladman** [comment]
all of that is handled with [init.sh](https://github.com/OSUOSC/open-source-club-website/blob/master/init.sh)

read [CONTRIBUTING.md](https://github.com/OSUOSC/open-source-club-website/blob/master/.github/CONTRIBUTING.md) to view instructions

if you feel these instructions should be moved else where go right ahead

**Comment by egladman** [comment]
the bowerfile, Gemfile and  `package.json` don't need documentation
- there **are** instructions on how to use the development server.
- the rakefile **is** documented
- the gruntfile **needs** documentation

**Comment by egladman** [comment]
@benlk I went ahead and created a [wiki](https://github.com/OSUOSC/open-source-club-website/wiki)

I think the wiki is more appropriate than creating a `/docs` directory

**Comment by benlk** [comment]
I dunno. Having a `/docs` dir means that the docs are included with `git clone`, while a wiki repo is  separate clone.

It is possible to add the wiki's repo as a submodule, but then it's a `git submodule update --init --recursive`, which is even more esoteric.

**Comment by Nefari0uss** [comment]
Both are fine. So long as the README indicates which one is used I think either one will work.

**Comment by Nefari0uss** [comment]
Both are fine so long as the README indicates which one is used. If it's wiki, a link should be good enough. Personally I hate dealing with submodules.

**Comment by egladman** [comment]
the main benefit of a wiki is that **anyone** can edit it, not just people with push access to the repo. 

@benlk I'll leave it up to you. If you do make a directory name it `/_docs` as this follows jekyll convention.

**Comment by egladman** [comment]
Some where we need to state that all helpers (i.e. `_helpers/*`) should be written in ruby.

**Comment by egladman** [comment]
I ran through the setup instructions on a clean install and had no trouble. People shouldn't have any trouble running the site locally

**Comment by smacz42** [comment]
#### WILL NOT FIX - new site
