### ISSUE TITLE
Backfill important images, files, presentations, etc from old site

### ISSUE THREAD

**Issue by notori0us** [CWDG/open-source-club-website#193]
Old posts from drupal site should have their attachments, such as images.

For instance, the [stallman article](http://opensource.osu.edu/announcements/2013/03/25/richard-stallman-visiting-osu/) should contain the pictures of the club with stallman (stallman1.jpg, etc)\

afaik, those files live on web3 at /var/www/drupal/sites/default/files 

-c

**Comment by egladman** [comment]
related issues #67 #58

**Comment by Nefari0uss** [comment]
#140

**Comment by smacz42** [comment]
#### WILL NOT FIX - new site
