### ISSUE TITLE
update constitution

### ISSUE THREAD

**Issue by egladman** [CWDG/open-source-club-website#204]
The constitution needs to be [updated](https://github.com/OSUOSC/open-source-club-website/blob/master/_posts/2014-03-28-constitution.md) since it was amended.

At a later date, I plan on eliminating the markdown version for the  v1.0.0 release for we don't have to manage two version of it.

**Comment by moore3071** [comment]
This will be handled once #208 is merged, but the switch from MD to PDF for the constitution would be a wise idea since the previous Constitution on the site wasn't the same as the PDF on file with the Union.

**Comment by moore3071** [comment]
Closed with #208
