### ISSUE TITLE
Make it easier for non-web-dev speakers to contribute

### ISSUE THREAD

**Issue by moore3071** [CWDG/open-source-club-website#207]
### Current behaviour

Those contributing are expected to use the helper posts and generate the site themselves to ensure no issues occur. For someone new to web-dev or just not comfortable with the current setup this can be intimidating. Additionally those able to merge PR are not aware of what is required for a post to work correctly.
### How to fix
- Provide a simple template for the posts that allows members to make a PR simply and even make the necessary changes via GH web-interface.
- Train those allowed to accept the PR on how a post should be structured.
- Perhaps simplify the build process to make the whole design a bit simpler.

**Comment by bsilvereagle** [comment]
A CONTRIBUTING.md or something similar that walks through how to create a simple post may be helpful. This document could also explain the build process and what's going on for any contributor that is not Ruby fluent.

**Comment by egladman** [comment]
I know this doesn't directly address your concerns however I felt the need to document it somewhere.  I simplified post generation. Instead of running `ruby _helpers/newPost.rb` you now just run `rake new:post`

**Comment by smacz42** [comment]
#### WILL NOT FIX - new site
