### ISSUE TITLE
Links in Atom.xml are incorrect

### ISSUE THREAD

**Issue by moore3071** [CWDG/open-source-club-website#212]
### Expected behavior
- Atom.xml will give links to the announcements or provide no link
### Actual behavior
- the domain name appears twice followed by the announcement path, or is preceded by another announcement.
### Steps to reproduce the behavior
- open https://opensource.osu.edu/atom.xml and click on a link to any post

**Comment by egladman** [comment]
@moore3071 could you elaborate? I'm having trouble understanding the issue.

**Comment by keeakita** [comment]
Right now the RSS feed produces links like:

```
https://opensource.osu.edu/opensource.osu.edu/announcements/2016/04/11/freeBSD/
```

Which is wrong and leads to a 404. That extra `opensource.osu.edu` shouldn't be in there.

**Comment by moore3071** [comment]
The link for the FreeBSD talk is this https://opensource.osu.edu/opensource.osu.edu/announcements/2016/04/11/freeBSD/ which duplicates the domain name. The next link is a concatenation of that and the next post giving https://opensource.osu.edu/opensource.osu.edu/announcements/2016/04/11/freeBSD/opensource.osu.edu/announcements/2016/04/03/package_managers/

**Comment by egladman** [comment]
oh okay. In chrome this isn't an issue, that's why this was never caught before.

**Comment by keeakita** [comment]
What's odd is that while a cursory glance at atom.xml seems to be fine, Firefox _and_ jenni both seem to exhibit this issue
