### ISSUE TITLE
404 on old resources

### ISSUE THREAD

**Issue by bsilvereagle** [CWDG/open-source-club-website#216]
### Expected behavior

The resources (images) on our previous [osuwireless on Ubuntu](http://opensource.osu.edu/tutorials/2008/07/29/osuwireless-in-ubuntu/) page should not 404.
### Actual behavior

The images 404. 
### Steps to reproduce the behavior

Visit the above link and click on any of the images or links such as "wireless icon" or "wireless tab".

**Comment by egladman** [comment]
i commented out the picture of the wifi config gui since I am unable to provide a newer picture. So we need someone to provide an updated picture. Here is the [file](https://github.com/OSUOSC/open-source-club-website/blob/master/_posts/2008-07-29-osuwireless-in-ubuntu.md) in question.

**Comment by bsilvereagle** [comment]
Already brought up in #193
