### ISSUE TITLE
[tutorial request] how to ssh into club systems

### ISSUE THREAD

**Issue by egladman** [CWDG/open-source-club-website#218]
it would be cool if someone wrote a tutorial explaing how to ssh into the club's systems.

**Comment by egladman** [comment]
tutorial can be found [here](https://github.com/OSUOSC/open-source-club-website/blob/tutorial-ssh_into_club_systems/_posts/2016-04-14-ssh-into-club-systems.md)

**Comment by benlk** [comment]
Stallman: `ssh username@stallman.cse.ohio-state.edu`
Idle2: `ssh username@opensource.osu.edu`

Mosh: Replace `ssh` with `mosh`

**Comment by egladman** [comment]
merged
