### ISSUE TITLE
SSL Cert has expired

### ISSUE THREAD

**Issue by egladman** [CWDG/open-source-club-website#225]
Either we need to contact the CSE department or use Let's Encrypt

**Comment by notori0us** [comment]
Talk to librewulf there's an SOP for getting cert

**Comment by keeakita** [comment]
Not sure what SOP means but our contact was Rowland who left. I'll have to open a ticket likely, hence the desire to evaluate Let's Encrypt. Sorry for the silence, family stuff this weekend has taken all my time.

**Comment by Nefari0uss** [comment]
[Let's Encrpyt](https://letsencrypt.org/) is something we should probably look into if it reduces our dependency on the CSE department. With it being late in the semester I dunno how quickly they'll respond back to what we need. Our current @OSUOSC/advisor and @OSUOSC/website-team should be aware of this.

**Comment by Nefari0uss** [comment]
@oslerw I think SOP means standard operating procedure.

**Comment by keeakita** [comment]
Resolved, just went with LE. Automated, rotating certs where a human never has to be involved is nice for both us and the department admins.
