### ISSUE TITLE
Improve favicon visibility

### ISSUE THREAD

**Issue by moore3071** [CWDG/open-source-club-website#232]
The current icon is difficult to see with a dark theme. The best way to improve it would be to add a black stroke to the circle, and colour the S polygon white with a black stroke. This should make the logo pop on any background.

Suggestions on this redisgn are appreciated.

**Comment by benlk** [comment]
For reference, the current image is various sizes of this:

![favicon-196x196](https://cloud.githubusercontent.com/assets/1754187/15903493/0fa7ab62-2d7b-11e6-86ed-1050955153f0.png)

``` html
  <link rel="icon" type="image/png" href="/dist/img/favicon-196x196.png" sizes="196x196"/>
  <link rel="icon" type="image/png" href="/dist/img/favicon-96x96.png" sizes="96x96"/>
  <link rel="icon" type="image/png" href="/dist/img/favicon-32x32.png" sizes="32x32"/>
  <link rel="icon" type="image/png" href="/dist/img/favicon-16x16.png" sizes="16x16"/>
  <link rel="icon" type="image/png" href="/dist/img/favicon-128.png" sizes="128x128"/>
```

**Comment by egladman** [comment]
i think it would be unwise to deviate from the branding guidelines. I'm against changing it.

EDIT: 
Well I guess it wouldn't hurt to fill the foreground (the "S") with `#FFF`, since it is currently transparent.

**Comment by moore3071** [comment]
yeah, I take back the black stroke iidea, and agree with changing the fill to white. The current logo is fine on light themes, but can be ugly on dark themes.  

There is one more odd case to consider, when the logo is put onto a background which is the same red as it is currently we might get unexpected results. We might change the branding guidelines to add an exception for this case.

**Comment by benlk** [comment]
The obvious solution is: Don't put it on a background with that same red.

That red is pretty dark, so an all-white logo, no fill on the S, would look pretty good

**Comment by moore3071** [comment]
That is the easiest solution, but we do need to double check that there is a note about that in the branding guidelines. For an example see the [OSU logo colour variations](https://brand.osu.edu/logo/#color-variations).

**Comment by notori0us** [comment]
I should note our club itself doesn't follow the branding guidelines with our logo. Oops. 

Check the bible (librewulf should have) for the historical color values we use

**Comment by egladman** [comment]
I added white to the favicon's background, and re-generated the favicons using [my favicon script](https://github.com/egladman/favicon.sh) 3abf4a1151e7cda922a834371c2c819cb2f75416
