### ISSUE TITLE
Provide contact information for club on site

### ISSUE THREAD

**Issue by benlk** [CWDG/open-source-club-website#244]
### Expected behavior

People browsing the site should be able to find information about how to contact the club, its officers, its mailnig list, its IRC channel, its post office box, and its advisor on the website
### Actual behavior

https://opensource.osu.edu/history/2015/07/23/officers/ appears to be the only contact information on the site, other than the social media links for Twitter (rarely updated) and GitHub

**Comment by Nefari0uss** [comment]
It particularly annoys me that on the bottom left, the third box is empty. We could easily put an IRC link on there or a mailto link.

**Comment by egladman** [comment]
@Nefari0uss i think your comment deserves it's own issue. You bring up a good point.

**Comment by egladman** [comment]
Is our twitter ever used?

**Comment by Nefari0uss** [comment]
@egladman : Twitter is rarely used. I don't know how currently has the handle. When I was doing a lot of the business for the club I tried to find out but I never quite got an answer. I was really hoping that at the very least we could set up a bot that would tweet whenever we're having a meeting/canceling one.

**Comment by egladman** [comment]
I think the last person that managed it was @notori0us, but I might be wrong. I really like the twitter bot idea.

**Comment by benlk** [comment]
Mailchimp automatically tweets through that handle with links to the archived newsletter: https://twitter.com/cwdgosu

**Comment by smacz42** [comment]
#### WILL NOT FIX - new site

**Comment by Nefari0uss** [comment]
Is this saying you will not fix on THIS repo and it'll work on the new site or you won't fix in general?

**Comment by smacz42** [comment]
https://opensource.osu.edu/info/ Should have officers, advisors

https://opensource.osu.edu/mailing-list/ Is the mailing list

and IDK the mailing addres/PO Box

I thought the email addr was on there somewhere, but if it isn't it should be.

----------

This was mainly regarding the twitter bot stuff. Any other static info should def be available
