### ISSUE TITLE
How is OSUOSC affiliated with the groups on its affiliation page?

### ISSUE THREAD

**Issue by benlk** [CWDG/open-source-club-website#245]
https://opensource.osu.edu/affiliations/

Right now, this page ^ is just a list of organizations. What are these organizations? Why are we affiliated with them? What are our guidelines of affiliation and do they reciprocate? Have we held events with those orgs in the past? In short, why are they listed there?

**Comment by Nefari0uss** [comment]
Furthermore, Capture the Flag doesn't even have a link to a website. A short small blurb as to what they do and why we are affiliated would probably be nice to have. 

My guess is that it's any club with whom we regularly work with to collaborate on an event or in which we have many members a part of (and work together to give talks on).

**Comment by egladman** [comment]
"Affiliations" might not be the best word. The original goal of the page was to highlight clubs that shared members.

**Comment by moore3071** [comment]
I'm currently working with another club organizer to try to create an aggregate site for tech clubs at OSU that we can link to instead. I have been considering adding other groups into affiliations such as Ohio LinuxFest, PyOhio, and the Electronic Freedom Alliance.

**Comment by smacz42** [comment]
#### WILL NOT FIX - new site
