### ISSUE TITLE
Content overflows on mobile and viewport cannot be resized

### ISSUE THREAD

**Issue by J3RN** [CWDG/open-source-club-website#250]
### Expected behavior

I expect to see all of the content, or at least be able to zoom out to be able to do so.
### Actual behavior

![screenshot_2016-10-29-21-42-57](https://cloud.githubusercontent.com/assets/2058614/19833915/5e835b52-9e21-11e6-975b-64b07018e1bc.jpg)

And I can't zoom out. Zoom in, yes, but that's not helpful.
### Steps to reproduce the behavior

Navigate to http://opensource.osu.edu/tutorials/2015/08/20/osuwireless/ on your phone :smile:

**Comment by egladman** [comment]
Thanks for pointing this out. I'll get it fixed

**Comment by smacz42** [comment]
#### WILL NOT FIX - new site
