### ISSUE TITLE
Club site should have a warrant canary

### ISSUE THREAD

**Issue by benlk** [CWDG/open-source-club-website#252]
### Expected behavior

Club site should have a warrant canary, because of services that the club provides to its members.

Information on warrant canaries:
- https://en.wikipedia.org/wiki/Warrant_canary
- https://www.canarywatch.org/faq.html

Example warrant canary: https://tutanota.com/blog/posts/transparency-report

### Actual behavior

Club site does not have a warrant canary.

**Comment by smacz42** [comment]
Club is within a government-owned college. A warrant canary would be useless as government agents already have root access to all servers.

So, what is the point of this again?
