### ISSUE TITLE
SP17 schedule discussion

### ISSUE THREAD

**Issue by moore3071** [CWDG/open-source-club-website#255]
This acts as a discussion area for the Spring 2017 schedule for the club.

**Comment by careyblack** [comment]
Please add a link to http://web.cse.ohio-state.edu/~haffners/linux/#/  for the talk on 2017-01-19

**Comment by moore3071** [comment]
Link to Stephen's talk is added in #259 in both the schedule and the link to his post.

**Comment by smacz42** [comment]
Site has been removed after username migration of CSE dept.
