### ISSUE TITLE
Use text in place of social icons

### ISSUE THREAD

**Issue by benlk** [CWDG/open-source-club-website#26]
Instead of this collection of icons:

<img width="378" alt="screen shot 2015-08-22 at 9 03 43 pm" src="https://cloud.githubusercontent.com/assets/1754187/9426467/4bd0262c-4911-11e5-9756-efba2481cf8b.png">

I think we should use plain text:
- Twitter: @OSUOSC 
- Email: info@opensource.osu.edu
- Github: @osuosc 
- Location: Caldwell 112

**Comment by egladman** [comment]
pull request #30 fixes this issue
