### ISSUE TITLE
Add meeting time to frontmatter and next meeting on index

### ISSUE THREAD

**Issue by moore3071** [CWDG/open-source-club-website#265]
### Expected behavior
Members expect to find the time along with the meeting date on the website.

### Actual behavior
The time is not included in meeting posts

### Steps to reproduce the behavior
*

**Comment by egladman** [comment]
I think a better solution is to append the `meeting_date` frontmatter variable with `@ 7pm`. That's what I used to do when I routinely updated the site. Imo the front page is unflattering when there is an odd quantity of "cards".

**Comment by smacz42** [comment]
#### WILL NOT FIX - new site
