### ISSUE TITLE
Missing FavIcon

### ISSUE THREAD

**Issue by moore3071** [CWDG/open-source-club-website#267]
### Expected behavior
Website would display club's logo or other significant image in the tab titlebar

### Actual behavior
No image is displayed

### Steps to reproduce the behavior
Load the page

Preferably the club logo would be added as the favicon for this website.

**Comment by smacz42** [comment]
Unable to reproduce, needs further info. \s

Checked with: https://realfavicongenerator.net/favicon_checker?protocol=http&site=opensource.osu.edu

https://github.com/OSUOSC/website/commit/4850c754803d2fbe9bc9a577aa1b1b7fd5740483 Closes issue
