### ISSUE TITLE
Jack is pushing via the github UI

### ISSUE THREAD

**Issue by JohnSimerlink** [CWDG/open-source-club-website#281]
### Expected behavior
Jack should use a command line

### Actual behavior
Jack is using the github website GUI

### Steps to reproduce the behavior
1) Ask jack to do a PR 2) Yell at him as he opens up the github.com GUI to edit the Markdown files. 3) Cry as he refuses to use the command line.

**Comment by jmoore53** [comment]
Can you provide logs, what you wrote in your terminal, and your code?

Can't solve the problem with out the requirements above...

**Comment by BrainBlasted** [comment]
Thanks for the issue, this is a pretty serious bug.

**Comment by oscziryak** [comment]
To quote Linus Torvalds:

> [Jack] do[es] literally insane things. [He] do[es] things that do not make sense. That makes all [his] arguments questionable and suspicious.
> […]
> I think we need something better than this garbage.
