### ISSUE TITLE
Website is inaccessible

### ISSUE THREAD

**Issue by andyklimczak** [CWDG/open-source-club-website#292]
Hey guys, grad checking in to see what you guys are up to at the start of a new semester and I  noticed the site is down? https://opensource.osu.edu I'm assuming this site/repo is the latest for the club

Thanks!

**Comment by vipermark7** [comment]
Hi there! We're getting in touch with the old officers and working on getting it back up.

**Comment by Nefari0uss** [comment]
Looks like the first failed build is here: https://travis-ci.org/OSUOSC/website/builds/484141798

**Comment by benlk** [comment]
> The command '/bin/sh -c bundle install' returned a non-zero code: 6
> The command "docker build -t website ." failed and exited with 6 during .

**Comment by benlk** [comment]
That build's commit was https://github.com/OSUOSC/website/commit/fbfa465355fa250bbcd4f5d57fd096e914910352 which only added a markdown file for a meeting.

So something changed in the build environment.

**Comment by andyklimczak** [comment]
I believe the Bundler 2 release is a part of the issue.

Is there a particular reason why `Gemfile.lock` is in the .gitignore?

**Comment by vipermark7** [comment]
I wish I could say, I don't really know why things are the way they are on
this site. :/

**Comment by Nefari0uss** [comment]
> I wish I could say, I don't really know why things are the way they are on
this site. :/

That makes several of us and I was around when this current iteration was being made... Personally I'd argue that the whole thing needs to be remade (when was Docker added? And is it *really* needed?) but that is perhaps a different conversation.

**Comment by andyklimczak** [comment]
I have a PR that fixes the travis build, which will allow the site to be properly deployed at least #293

**Comment by andyklimczak** [comment]
I'm not 100% convinced the PR will solve the site being up or not, but it turned your travis build green.

Have an officer try [this step](https://github.com/OSUOSC/website#for-officers), then we'll know for sure

**Comment by benlk** [comment]
Connection times out.

`dig opensource.osu.edu in A` replies that the domain's IP address is 164.107.116.158

```
$ ping 164.107.116.158
PING 164.107.116.158 (164.107.116.158): 56 data bytes
Request timeout for icmp_seq 0
Request timeout for icmp_seq 1
^C
--- 164.107.116.158 ping statistics ---
3 packets transmitted, 0 packets received, 100.0% packet loss
```

The server isn't accessible.

**Comment by dominikWin** [comment]
The OSC office has not had network access for some time now. I'm working on getting networking back up, but at the moment it is unclear how long this will take.

**Comment by andyklimczak** [comment]
You could host the jekyll pages with github pages instead of using osu infrastructure/stallman2, and point `opensource.osu.edu` to the new domain (but where's the fun in that).

**Comment by Nefari0uss** [comment]
Seems like the site is still down. @dominikWin does the OSC office still have no network access?

@andyklimczak That's certainly a possibility although I know in the past, there was a preference for using "our" own infrastructure as much as possible.

On a more general note and the risk of being that guy...might I suggest a full site remake? The current setup seems rather problematic, decisions were made that no one quite knows or understands anymore, and a lot of the existing stuff being used is outdated or somewhat archaic. I am by no means suggesting that it would be easy but there might be value in creating a new site using a more modern setup such as Webpack to handle asset management, a CI build pipeline, Babel for browser support, etc. If a framework is desired, then you can use something like Materialize or Bulma for styling and build on top of it. Similarly, you can use a web frame work if desired like React of VueJS to create an SPA. Furthermore, you can ensure that it is fully ADA compliant for accessibility as well as making sure that it is mobile friendly. (I guess Docker is fine to have, especially if you want to ensure that everyone has the same build.) It would be a lot of work but I think there would be long term value in doing so.

**Comment by joshuaekingsbury** [comment]
Until the original domain is properly configured, I've set it to the default pages link just so its available.
http://osuosc.github.io/website/

We continue to work on updating the information.

**Comment by Nefari0uss** [comment]
@joshuaekingsbury The styling (and maybe JS) is broken.

**Comment by egladman** [comment]
@Nefari0uss perhaps this should be made into a separate issue, but i'll leave that thoughts below...

When I transitioned the site from Drupal to Jekyll back in 2015/16 (I don't remember the specific date) the build the substantially simpler. You could argue there were a few intricacies, but i had helper scripts (macOS/Linux compatible) to do the heavy lifting. I also documented everything before i left.

The current website/build has definitely gotten out of hand. Having some sort of CI is a good idea, but i too think docker and babel is overkill. Instead of cross-compiling javascript it makes sense to make the site work seamlessly with and without javascript. (i haven't tested if this is already the case). It's not the end of the world if the site doesn't work on ancient versions of IE. 

My memory is a bit fuzzy, but i believe the current site was written by @smacz42. Andrew might be able to shed light on the current build.

**Comment by Nefari0uss** [comment]
I hope my comment didn't come across as accusatory. It's just that the site has gone through so many maintainers, each with their own philosophy and decision making that context gets lost upon each transition. It may have started off well but at this point it's turned into a different beast.

As for some of the components...
Docker itself isn't necessary but it's...fine? I don't feel strongly about it either way. It's use case here is to ensure that whatever changes someone does ultimately works in the same deployment as it would in production. Given that each student will have varying levels of knowledge and dependencies may fall out of sync, I figure it's just one way of ensuring that it runs. (No more `it works on my machine`.)

As for Babel, I think there's tremendous benefit in being able to use some of the newer versions of ES6/7/8. Being able to write utilizing classes (very nice syntactic sugar), async / await support when dealing with promises, rest spread operators, object de-structuring, and a whole host of stuff that makes it much nicer to write JS in. TLDR: You'll pry the ability to use `async / await` out of my cold, dead hands.

I suppose that decision is to be made by whomever decides to re-write the site IF that's the route the current members decide to take.

**Comment by egladman** [comment]
>I hope my comment didn't come across as accusatory

Not in the slightest. 😃 

> I suppose that decision is to be made by whomever decides to re-write the site IF that's the route the current members decide to take.

Exactly. I'm not concerned how the goal is accomplished as long as things are documented.

**Comment by smacz42** [comment]
I'd be happy to answer any questions that come up. 

On November 14, 2019 6:27:16 PM EST, Eli Gladman <notifications@github.com> wrote:
>>I hope my comment didn't come across as accusatory>
>Not in the slightest. 😃 >
>>
>> I suppose that decision is to be made by whomever decides to re-write
>the site IF that's the route the current members decide to take.>
>>
>Exactly. I'm not concerned how the goal is accomplished as long as
>things are documented. >
>>
>-- >
>You are receiving this because you were mentioned.>
>Reply to this email directly or view it on GitHub:>
>https://github.com/OSUOSC/website/issues/292#issuecomment-554132614

-- Andrew Cziryak
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Nefari0uss** [comment]
@smacz42 I'm not sure if you can see the full issue history via email. Might be best to take a read of the whole thing and then give your thoughts.

**Comment by smacz42** [comment]
> @joshuaekingsbury The styling (and maybe JS) is broken.

I concur. I'll take a look to see what might have happened.

**Comment by dominikWin** [comment]
Closing, site back up and rewritten.
