### ISSUE TITLE
https://opensource.osu.edu/ does not redirect to https://osuosc.org/

### ISSUE THREAD

**Issue by luketrenaman** [CWDG/open-source-club-website#299]
The link in the Github about section points to opensource.osu.edu which doesn't seem to respond / redirect to the site. Not sure if this is a specific outage with osu or something else.
![image](https://user-images.githubusercontent.com/46632227/174332252-77348b29-1069-4e29-88b5-949743095047.png)

**Comment by dominikWin** [comment]
It's not an outage or anything. Essentially, OSU doesn't want to host *anything* that they didn't create or don't fully control (ie. only supporting things from top-down directives, not grassroots or student-lead stuff). A lot of this is security, disability, and branding compliance which no employee wants to deal with unless their job forces their hand. Unfortunately, all osuosc stuff is moving away from OSU domains for good. There are some groups that still run of osu.edu subdomains, but those groups are both larger than us and likely overdue for this to happen to them too.

Any links to opensource.osu.edu should be changed.

**Comment by OrangeDrangon** [comment]
Link on github homepage updated.
