### ISSUE TITLE
We should have a page linking to ....

### ISSUE THREAD

**Issue by benlk** [CWDG/open-source-club-website#34]
- [ ] affiliated student orgs at OSU
- [ ] organizations we endorse

And yes, the content of this page is going to be political.

**Comment by egladman** [comment]
good idea

**Comment by egladman** [comment]
@Nefari0uss Could you supply me with a list of affiliated student organizations and/or organizations that the club endorses?

**Comment by Nefari0uss** [comment]
Do you still need this?

**Comment by egladman** [comment]
@Nefari0uss can you think of any other student orgs that we should link to. [This](https://github.com/OSUOSC/open-source-club-website/blob/master/affiliations.jade) is the file is question. Otherwise no.
