### ISSUE TITLE
Link with weather in Columbus

### ISSUE THREAD

**Issue by myano** [CWDG/open-source-club-website#56]
Make the clouds change based on weather in Columbus, OH.

Obtain a free API-key for wunderground.com and ping it once every 5 minutes or so to cache it (or how ever often you can while it is still free) and update the cloudiness and make the clouds rain if it is raining.

**Comment by myano** [comment]
So it seems wunderground.com allows 500 calls a day. That works out to about 1 call every 3 minutes, which seems sufficiently frequent enough to update the page (and cache the result). :D

**Comment by myano** [comment]
I think you'll want the json_response['current_observation']['weather'] to get the string of what the current weather is. You'd get something like: "Mostly Cloudly" or "Cloudy" or "Overcast" or "Raining" etc...

**Comment by egladman** [comment]
it would be cool if we changed the background color to indicate whether or not it was morning, noon, evening, and midnight.

**Comment by myano** [comment]
@egladman Yes! That'd be cool too. We could add a moon and a sun to the page! :D

**Comment by myano** [comment]
Perfect, here we go. We can grab the sunrise, sunset, and percent of illumination of the moon too!

http://www.wunderground.com/weather/api/d/docs?d=data/astronomy

**Comment by egladman** [comment]
I started playing around with the idea: [gist](https://gist.github.com/egladman/147893094191a10a3142)

Here is a live [demo](http://codepen.io/egladman/pen/dYONKR).

**Comment by benlk** [comment]
All I can say to this is :+1:

**Comment by smacz42** [comment]
### WILL NOT FIX - old site
