### ISSUE TITLE
Ease deploy by setting up git hooks

### ISSUE THREAD

**Issue by keeakita** [CWDG/open-source-club-website#60]

**Comment by egladman** [comment]
[possible solution](https://github.com/developmentseed/jekyll-hook)

**Comment by keeakita** [comment]
Since gluster appears to be falling over when you install a gem on web3, I can't complete this until we go back to our NFS based home directories. This is stalled until then.

**Comment by keeakita** [comment]
This is "done", pending somebody other than me testing it. I'm going to create a new issue for making the deploy integrated in a grunt task.
