### ISSUE TITLE
Some pages missing images from drupal migration

### ISSUE THREAD

**Issue by keeakita** [CWDG/open-source-club-website#67]
```
20:00:34 ilar │ https://opensource.cse.ohio-state.edu/tutorials/  <-- broken images
```

**Comment by egladman** [comment]
@oslerw could you provide me with the assets folder from the deprecated drupal site?

**Comment by egladman** [comment]
update?

**Comment by keeakita** [comment]
Didn't realize this issue was assigned to me. I have virtually no time this week to do anything, but will get back to you next week.

**Comment by egladman** [comment]
bump

**Comment by keeakita** [comment]
There's about 200mb of these -- how would you like me to get them to you? I have a .tar.gz downloaded.

**Comment by egladman** [comment]
@moore3071 could you handle this?
