### ISSUE TITLE
update to ruby 2.2.3

### ISSUE THREAD

**Issue by egladman** [CWDG/open-source-club-website#83]

**Comment by keeakita** [comment]
Don't forget to update the .ruby-version file if you do this

**Comment by egladman** [comment]
[jekyll-assets](https://github.com/jekyll/jekyll-assets) introduced breaking changes in their gem, so I have to update it, before we can merge [ruby-2.2.3](https://github.com/OSUOSC/open-source-club-website/compare/ruby-2.2.3) into master.

**Comment by egladman** [comment]
fixed 434127bbcf60f4925401670ea98fecd20d6f1e18
