### ISSUE TITLE
Grunt not using bundler's gems

### ISSUE THREAD

**Issue by keeakita** [CWDG/open-source-club-website#96]
Compiling on my machine with `grunt build` produces the following:

`You have already activated sass 3.4.19, but your Gemfile requires sass 3.4.18. Prepending`bundle exec`to your command may solve this. (Gem::LoadError)`

I believe this has something to do with me having a newer system version of sass, but that should be irrelevant since the project should be using the bundler version of gems. I'm able to build with `bundler exec grunt build`, but we should probably update the Gruntfile to use `bundle exec jekyll build`.

**Comment by egladman** [comment]
let me know if the issue still persists.
